### ISSUE TITLE
First stab at an implementation of the server

### ISSUE THREAD

**Issue by jcelerier** [mrRay/OSCQueryProposal#21]
Hello,

Here (https://github.com/jcelerier/coppa) is a tentative attempt (about 8hrs of work so not very advanced, and quite messy) at an implementation of OSCQuery using websockets.
This is done in pure C++14 (mostly for fun) (and requires boost, and the latest version of clang to build). It's header-only. 

What works : 
- Adding parameters 
- Querying the whole namespace, single paths, and attributes of parameters via http and getting a reply in json.

What isn't done :
- Units. I'm lazy.
- Certainly a ton of thing that I forgot.
- Return of HTTP error codes.
- Listening
- path_changed

What differs :
- The json keys are in lower case because I was starting to get a carpal syndrome channel while keeping Maj down.
- JSON requires the '/' character in strings to be escaped. So in the full path it looks like "\/a\/b\/c".
- '?' instead of '#' in queries : browsers don't send what's after the '#' in the HTTP request, hence it's a pain to test.

Notwithstanding the fact that the json part in `coppa.oscquery.hpp`  is an exercice in ugliness, it should give a quick example (overall it's < 600 lines of code) in order to go forward with the spec.

Also, I worked on something generic enough for being able to adapt to other existing query protocols (like Minuit), with a mostly compile-time way to define parameters from simple attributes.

**Comment by jcelerier** [comment]
I am working on dynamic namespace updating right now; some notes :

 - it seems quite hard to use http:// as a protocol for listening, since it is for one-shot queries and there is no way to get a long-term handle. For this, the websocket ws:// protocol is more suitable, but it can't be used in a navigator for instance.
- All the server updates are sent by websockets (whether they are value / attributes) since in this case we don't need to have an OSC receiver in the client. The only required OSC connection would then be client -> server to set the new value of a parameter
Hence the message :
{
    "path_changed" : "/a/path/to/some/parameter"
    "description" : "the new description"
}

- What I have yet to do (in addition to the previous list) : 
  - Error checking (for now, if there is some invalid (and maybe some valid) data, it will crash !
  - Finish the TODO's in the code
  - Updates when parameters are added / removed.

Listening seems to work, as well as setting values on the server (I used oscpack).

**Comment by mrRay** [comment]
howdy-

thanks for your interest in this- and, more importantly, your work on an implementation.  would you mind if i linked to your repos in the proposal?

>“it seems quite hard to use http:// as a protocol for listening, since it is for one-shot queries and there is no way to get a long-term handle. For this, the websocket ws:// protocol is more suitable”

i think that’s pretty much right in line with the proposal?

>“(about 8hrs of work so not very advanced, and quite messy)”

hey, that’s more time than i’ve been able to spend writing code for this, and i for one appreciate your contribution.  it's good to know other people have this itch, too.  thanks!


cheers
: : ray

**Comment by jcelerier** [comment]
> would you mind if i linked to your repos in the proposal?
Please do! However this is not even alpha-quality.

> i think that’s pretty much right in line with the proposal?

I'm referring to this part : 
> As mentioned earlier, the "query string" part of a URL can be used pass variables/parameters from client to server- a client could use this to request that the server start/stop streaming values to it (http://ip:port/abs/path?listen=true). 

The problem here is that when the server receives a "traditional" http request, the connection is not meant to be lasting, but only to be long enough to send a single reply to the client. If one wants to have a lasting connection between client and server (so that the server can keep track of which client is listening what), the websocket protocol should be used to send and receive messages. From the point of view of the code, this is very similar, but it just won't be introspectable by just looking at the http GET part. 
But I've been fiddling with websockets for only about a week so maybe I'm telling tons of incorrect things based on the assumptions taken in the lib that I used :)

**Comment by jcelerier** [comment]
Another thing that is not clear for me when reading the spec (but I'm not a native speaker so maybe it's that :) ) is the case of changes in namespaces.

Does the `path_changed`  work in "absolute mode" ? 
i.e. when a client receives 

` { path_changed : "/foo/bar" }` should he assume that /foo/bar is now a leaf without any attributes or children ? 

Would it not be more efficient (at the price of more complexity) to have special commands for updating attributes and children ? 
Because for instance if we have a parameter /foo/baz with an integer value and a min / max, we can't simply change the max by doing ` { path_changed : "/foo/baz" range : [ [ 0 150 null ] ] }`

since this would remove all the children nodes and other attributes ?

**Comment by mrRay** [comment]
>“Would it not be more efficient (at the price of more complexity) to have special commands for updating attributes and children ? 
Because for instance if we have a parameter /foo/baz with an integer value and a min / max, we can't simply change the max by doing { path_changed : "/foo/baz" range : [ [ 0 150 null ] ] } but we have to resend the whole sub-namespace of /foo/baz since this would otherwise remove all the children nodes and other attributes ?”

when i wrote the proposal i only had coalesced changes to the structure of the address space in mind, so i expected that the whole sub-namespace would get sent.  in retrospect, this is silly and you make a very good point.

what if a PROPERTY_CHANGED (or maybe ATTRIBUTE_CHANGED?) is sent if we just want to change something like a max range?  i haven’t put a ton of thought into this, but perhaps something as simple as only passing the attributes that changed would work?  so, for example, changing the range could look like this:

~~~
{
	“ATTRIBUTE_CHANGED”: {
		“/foo/baz”: {
			“RANGE”: [0 150 null]
		}
	}
}
~~~

…of course, “PATH_CHANGED” still suffers from the limitation you mentioned- the entire sub-namespace of the passed path would have to be re-sent.  we could take this a step further and potentially have “PATH_ADDED”/“PATH_REMOVED” calls too- or is that going too far?

thoughts?

**Comment by lov** [comment]
Hello,

> JSON requires the '/' character in strings to be escaped. So in the full path it looks like "\/a\/b\/c".

Regarding to the JSON docs, only the reverse solidus '\' should be escaped (Page 4: http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf)

> '?' instead of '#' in queries : browsers don't send what's after the '#' in the HTTP request, hence it's a pain to test.

Nice catch! +1 for using '?' instead of  '#', since the hash mark identifies a fragment which should be handled on the client side regarding to the HTTP specification (http://www.w3.org/Protocols/HTTP/Fragment/draft-bos-http-redirect-00.txt), but that data should not be sent to the server anyway.

**Comment by jcelerier** [comment]
>   JSON requires the '/' character in strings to be escaped. So in the full path it looks like "\/a\/b\/c".

Nice ! So far the libs I've tried all escaped the solidus. I'll start spamming them with bug reports.

**Comment by lov** [comment]
> Nice ! So far the libs I've tried all escaped the solidus.

JSON doesn't require you to do that, it allows you to do that - so this is definitely something we should care about.
